### ISSUE TITLE
Initialize AWS EC2 - AWS S3 services

### ISSUE THREAD

**Issue by oztasoi** [bounswe/bounswe2020group8#100]
**Describe the feature**
To deploy our product, a repository and a computer needs to be activated in Amazon Web Services.

**Describe solutions you've considered**
1. Create profiles to be accessed by all of backend members.
2. Create EC2 instance
3. Create S3 bucket 

**Additional context**

**Comment by mtyazici** [comment]
I have an EC2 instance running for backend deployment it has been running for 2 days. I also use an automated script for updating the app to the new version.

**Comment by oztasoi** [comment]
Nice job! Closing the issue now. 🚀
