### ISSUE TITLE
Initialize MongoDB database

### ISSUE THREAD

**Issue by oztasoi** [bounswe/bounswe2020group8#101]
**Describe the feature**
To store data for our application, it is needed to be initialized.

**Describe solutions you've considered**
1. By using credentials provided by Kaan, create and run a MongoDB instance in EC2.

**Additional context**

**Comment by burakberk** [comment]
1. New EC2  instance created to hold the mongoDB.
2. mongDB initialized in EC2 instance.
3. mongDB tested OK.
4. Admin user created for backend team to access mongoDB.
5. Credentials of admin user shared with the backend team.

**Comment by oztasoi** [comment]
Since the initial trial of initializing the database has some unexpected outcomes, we've decided to change the assignee and restart the issue from scratch. @kaandura will be the next assignee for this issue. 👍

**Comment by kaandura** [comment]
I deployed the database and shared the credentials with the team.
