### ISSUE TITLE
Add Github Actions For Deployment

### ISSUE THREAD

**Issue by oztasoi** [bounswe/bounswe2020group8#102]
**Describe the feature**
To deploy in an automated approach, it is needed to be implemented.

**Describe solutions you've considered**
1. Create a YAML file considering GitHub Actions syntax

**Additional context**

**Comment by mtyazici** [comment]
We are using Ansible this purpose, I integrated it with github actions. However there is still some testing to do, I will create a PR when testing is finished.

**Comment by mtyazici** [comment]
Auto deployment for development works correctly, I am closing the issue.
