### ISSUE TITLE
Research about W3C

### ISSUE THREAD

**Issue by goksubaser** [bounswe/bounswe2020group8#114]
As the project description said, we need to code according to the World Wide Web Consortium (W3C) standards. Therefore we all need to research on the subject. Since we need to code according to this protocol, the due date is 16.11.2020 05:59

To research, we should use the following references:
       1. The World Wide Web Consortium – Activity Streams, Accessed: February 2020.
       2. The World Wide Web Consortium – Standards, Accessed: February 2020. 

- [x] Afra Akbaş

- [x] Burak Berk Özer

- [x] Ahmet Yiğit Gedik

- [ ] Nursima Çelik

- [ ] Onur Enginer

- [ ] Kaan Dura

- [ ] Yasin Kaya

- [ ] Özgürcan Öztaş

- [x] Göksu Başer

- [x] Öncel Keleş

- [x] Nazım Berke Metin

- [x] Muhammet Tayyip Yazıcı

**Comment by afraarslan** [comment]
I did research and found its documentation. You can also check [this site](https://www.w3.org/TR/activitystreams-core/). I think that it is well-explained with various examples.

**Comment by oncelkeles** [comment]
The examples in the link Afra shared are very informative, thanks 💯

**Comment by burakberk** [comment]
I believe everyone already researched this topic and the issue is obsolete.
