### ISSUE TITLE
Research about GDPR and KVKK

### ISSUE THREAD

**Issue by goksubaser** [bounswe/bounswe2020group8#115]
As the project description said, we need to follow rules defined by GDPR and KVKK. Therefore we all need to research on the subject. The due date is 23.11.2020 05:59

- [ ] Afra Akbaş

- [ ] Burak Berk Özer

- [ ] Ahmet Yiğit Gedik

- [ ] Nursima Çelik

- [ ] Onur Enginer

- [ ] Kaan Dura

- [ ] Yasin Kaya

- [ ] Özgürcan Öztaş

- [ ] Göksu Başer

- [ ] Öncel Keleş

- [ ] Nazım Berke Metin

- [ ] Muhammed Tayyip Yazıcı

**Comment by burakberk** [comment]
I believe everyone already researched this topic and the issue is obsolete.
