### ISSUE TITLE
Recommendations about project name

### ISSUE THREAD

**Issue by goksubaser** [bounswe/bounswe2020group8#17]
Leave recommendations about the project name. Next meeting we will discuss.

**Comment by afraarslan** [comment]
Çarşı

**Comment by nursimacelik** [comment]
awning (tente)
vitrin

**Comment by ykaya932** [comment]
(Online) Bazaar

**Comment by oguzhanozboyaci** [comment]
BuradanAl

**Comment by afraarslan** [comment]
Sahafcım

**Comment by ykaya932** [comment]
Deadline Friday 23.59

**Comment by goksubaser** [comment]
I'm closing this because poll is online with existed suggestions in https://doodle.com/poll/b3iw8fzyr9pd8e27
