### ISSUE TITLE
About Ömer Topuz

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group8#18]
Dear members of Group 8,

As I stated in my Piazza post, please communicate with your team member Ömer Topuz via his e-mail address (omer.topuz@boun.edu.tr).

You may close this issue after having contact with him.

**Comment by O-1-Oz** [comment]
Merhabalar, conflictim olduğu için derslere gelemiyorum. Dersle bağlantı kurmaya çalışıyorum ve tel de kullanmıyorum. Benimle iletişim kurup bilgilendirirseniz sevinirim... Teşekkürler

**Comment by afraarslan** [comment]
Github ve slack uzerinden iletisim kurabiliriz.

**Comment by O-1-Oz** [comment]
Tamam gitten güzel olur. Teşekkürler,

**Comment by afraarslan** [comment]
Ömer slack için email adresini verir misin?

**Comment by nursimacelik** [comment]
Ömer şuan slack'te. Bu yüzden issue'yu kapatıyorum.
