### ISSUE TITLE
Fix Signup/Login UI design

### ISSUE THREAD

**Issue by afraarslan** [bounswe/bounswe2020group8#186]
**Describe the feature**
We implemented the sign-up and login page but there are some UI issues. We are going to design them in a better way.

**Describe solutions you've considered**
We decided the UI design can be as follows:

![image](https://user-images.githubusercontent.com/32341138/100121180-df7f6f00-2e89-11eb-8405-e636ecdd260b.png)

**Additional context**
Google Signup/Login also will be updated according to these changes.

**Comment by afraarslan** [comment]
I'm assigned this issue to @oncelkeles. He will design this feature.

**Comment by oncelkeles** [comment]
Hey! You can check it out from web-feature/loginsignup branch and give your feedbacks! I think it looks ready ✌️
