### ISSUE TITLE
Questions ask to customer

### ISSUE THREAD

**Issue by goksubaser** [bounswe/bounswe2020group8#19]
While filling requirements some questions will may arise. Put them here in comments so we can create a Question to Customer page in wiki to ask our customer.

**Comment by goksubaser** [comment]
Can a vendor user buy, comment or rate other products or is he need to open a customer account to do these?

**Comment by goksubaser** [comment]
Which categories should the program support or can the category tags be designed by vendors themselves (this causes a big category pool generation and also lots of repetition)

**Comment by goksubaser** [comment]
Can a vendor direct message another user (customer or vendor or admin)? Or just can reply?

**Comment by goksubaser** [comment]
Can a guest user add products to the cart and buy without an account?

**Comment by goksubaser** [comment]
What should be the permissions of admin?

**Comment by goksubaser** [comment]
In what kind of situations vendors might communicate with platform admins?

**Comment by goksubaser** [comment]
what kind of notifications might be done (especially for vendors)?

**Comment by ykaya932** [comment]
What is the desired performance in terms of response time?

**Comment by ykaya932** [comment]
Is there any preferred encryption algorithm to store passwords.

**Comment by ykaya932** [comment]
In which versions of Android should the product work?

**Comment by ykaya932** [comment]
In which web browsers should the product work? (And it versions)

**Comment by ykaya932** [comment]
What should be the least uptime percentage?

**Comment by ykaya932** [comment]
Should there be maintenance on regular basis? If so, what should be the frequency? What should be the duration of the maintenance?

**Comment by ykaya932** [comment]
What should be the language of the product? English, Turkish or both?

**Comment by ykaya932** [comment]
What is the expected number of users that use the product? How many people could be able to use the product at the same time without a problem?

**Comment by nursimacelik** [comment]
1. What is necessary while registering other than e-mail address and password (name, surname)?
2. Will customers have a profile page?
3. What will be available in the vendor's/customer's page to be seen?

**Comment by oguzhanozboyaci** [comment]
Will it be a local website or global?

**Comment by ykaya932** [comment]
Will the sold products 2nd hand(used) or brand new?

**Comment by afraarslan** [comment]
Can a guest user rate a product?
