### ISSUE TITLE
Implement Admin Panel - Accounts and Categories

### ISSUE THREAD

**Issue by oncelkeles** [bounswe/bounswe2020group8#195]
**Describe the feature**
There should be an account suspend and delete feature in the admin panel. Also, the admins shall be able to add and remove categories.

**Describe solutions you've considered**
The admin panel will be in the form of profile page.

**Additional context**
Requirements: 1.1.13.1, 1.1.13.2

**Comment by oncelkeles** [comment]
The acounts section of the admin panel is running 🏃

**Comment by ahmetyigitgedik** [comment]
Categories section of the admin panel has been finished! :fire:
