### ISSUE TITLE
About issues without proper information

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group8#20]
Dear all,

You are mostly OK so far about issues, but I will make a warning just in case.

Please note that each issue should contain **at least one assignee and label**. Besides these, it should also contain **an explanatory title** as well as **a proper description**. Moreover, even though it is not always possible, try to specify the **priority level** and the **deadline** while writing the issues. Last but not least, try to **distribute the issues equally** among team members both in terms of assignee and owner of the issue (i.e., rather than a few people, every single team member should open a sufficient amount of open issues).

Best,
Meriç

**Comment by nursimacelik** [comment]
We added a checklist for the tasks that everyone is responsible, like watching git tutorial, as this way is appreciated by the instructor. But who should be assigned to such a task?

**Comment by mericturan** [comment]
Dear Nursima,

As I stated, you should assign **at least** one assignee to each issue. It means that you can assign multiple assignees (even everyone) to an issue. Therefore, for such a task, the assignee should be the whole team.

Also, as a suggestion, you can additionally create a label named "Everyone" or "Group Work" to better describe such issues.

Best,
Meriç

**Comment by uskudarli** [comment]
The instruction said that she prefers having an issue per person, and did
not say she prefers checklists.

A checklist is better when you need to do several subtasks before a task is
complete, for example: [] Select a good git repository [] Summarize what
the repository is about [] Describe the desirable aspects with respect to
project management

When you do this, there is a clear description of important sub-tasks that
must be completed for the task to be considered complete. And it is
assigned to a person.

For issues like watch git video (description with video etc), you assign to
each person. The persons who complete the issue will close the issue they
are assigned to. You could make a checklist that explains what they should
do if you want detailed work done w/r to watching (to validate that it was
indeed watched).  If 4 people watched and 8 did not, the 4 people can not
indicate that they completed their tasks.

In general try to avoid assigning multiple people. Exceptions can be tasks
like brainstorming meetings...

**Comment by mericturan** [comment]
I hope our message reached the dear members of Group 8.
