### ISSUE TITLE
General wiki page design

### ISSUE THREAD

**Issue by goksubaser** [bounswe/bounswe2020group8#21]
We need to design our wiki page in a more presentable format. Such as a group photo, a group logo in main page and a tidy sidebar.

**Comment by goksubaser** [comment]
We should discuss this in our upcoming meeting. Also, I can be a volunteer if no disagreement.

**Comment by afraarslan** [comment]
We designed the sidebar which all work that we have done so far can be found. We also decided our group name and our logo and added them onto [the wiki page](https://github.com/bounswe/bounswe2020group8/wiki)
