### ISSUE TITLE
Signup error 

### ISSUE THREAD

**Issue by afraarslan** [bounswe/bounswe2020group8#227]
**Describe the bug**
I encountered an error while test our signup method. When a user types an inappropriate password (not a strong message) and clicks the signup button, it gives the error (given in Screenshots).

**Code location**
It says it is in:  `src/components/Login/LoginComponent.js:174`
We sent a POST request for signup. The backend response gives an error, but it does not contain response data. We should fix this according to the response.

**Expected behavior**
It should say that the password should be strong and ask for a new one.

**Screenshots**
![image](https://user-images.githubusercontent.com/32341138/101825186-58dfb880-3b3e-11eb-98b8-c32ae2cdbb46.png)

**Additional context**
I have realized this error when I tested the case of what happens when a user types a weak password.

**Comment by oncelkeles** [comment]
Resolved and also fixed error messages not showing in the signup form ✌️
