### ISSUE TITLE
Update the Communication Plan

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#24]
According to comments made by Meric, our communication plan lacks information. We need to update the plan.

**Comment by ykaya932** [comment]
I updated the communication plan page. I ask for your review. If someone reviews the communication plan, please comment that you reviewed and close the issue.

**Comment by oguzhanozboyaci** [comment]
We can add a skype call for who couldn't attend the face to face meetings.

**Comment by ykaya932** [comment]
Done. @OnurEnginer,  could you check the current communication plan.

**Comment by OnurEnginer** [comment]
I think that covers everything, thank you.
