### ISSUE TITLE
Docker Compose image registry

### ISSUE THREAD

**Issue by mtyazici** [bounswe/bounswe2020group8#248]
**Describe the feature**
I opened a Docker Hub account for our app. Right now, the image name in the "docker-compose.yaml" file is "amoged97/carousel-frontend", it should be changed to "carouselapp/carousel-frontend"

**Comment by ahmetyigitgedik** [comment]
I have changed the image name, then created a pull request in order to update the web branch. I will let you know when my pr request is confirmed by other members of the frontend team. 💯
