### ISSUE TITLE
Convention is needed for labels

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#25]
While some labels start with an uppercase letter, some start with a lowercase letter. Also, there are labels called "Status:X", so IMO we can have labels called "Priority:X". For those reasons, I think we should find a convention and stick to it. I am assigning @burakberk for this issue if help is needed you can assign some people to this issue.

**Comment by burakberk** [comment]
Priority:X was used by many other groups. Hence, it was not the initial choice. Nevertheless, since it is a trivial solution to naming, I believe it can be used again.
