### ISSUE TITLE
Update and Review the Non-Functional Requirements

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#26]
An update is needed for Non-Functional Requirements. I am pasting the comment by Meric: 
"In non-functional requirements, separate security from privacy. Enlarge the non-functional requirements, and apply the aforementioned comments for non-functional requirements as well (e.g., replace X with a number until the deadline, add W3C activity stream as a requirement)."

**Comment by ykaya932** [comment]
Göksu will review after completion. Deadline for Yasin Saturday 23.59 and deadline for Göksu Sunday 23.59 also Glossary will be filled

**Comment by ykaya932** [comment]
@goksubaser, I've updated the Non-Functional Requirements. Could you please check them?

**Comment by goksubaser** [comment]
I've corrected some English mistakes. In addition to that, I've transferred 2 items to the System Requirements part. I couldn't find any missing definition for the Glossary part. I'm closing this issue
