### ISSUE TITLE
Creating a doodle for group name selecion

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#27]
Göksu will create a doodle for the group name. The doodle will be created until Saturday at 10.00. The conclusion will be announced on Sunday.

**Comment by goksubaser** [comment]
https://doodle.com/poll/b3iw8fzyr9pd8e27 This link is the poll for the group name. Also, I've shared it in the slack. The conclusion will be announced at Sunday 23.59 in here and Slack.

**Comment by goksubaser** [comment]
Çarşı and BuradanAl won with a tie of 3 people voted out of 4 total voters. The group decided to postpone the decision after the customer meeting.

**Comment by goksubaser** [comment]
New Deadline 11.04.2020 After that new poll will be opened.

**Comment by nursimacelik** [comment]
lazy shop
lazy shopping
lazy
bargain hunt
bargain hunters
carousel
golden hall

**Comment by alialperendurak** [comment]
[Group Name Selection](https://doodle.com/poll/m3fsrxda3kcf3y2n) is here with 15 options. The result will be announced both here and slack.

**Comment by afraarslan** [comment]
We decided on our group name the **_CAROUSEL_**
You can check our [wiki page](https://github.com/bounswe/bounswe2020group8/wiki) to see our logo.
