### ISSUE TITLE
System Requirement Review

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#29]
System Requirements will be reviewed and completed and glossary will be filled with unclear definitions according to the feedback in the piazza. Deadline Sunday 23.59

**Comment by goksubaser** [comment]
There is enumeration mistakes at system requirements. Please correct them while reviewing

**Comment by oguzhanozboyaci** [comment]
Could you check and if everything is ok, close issue @goksubaser ?

**Comment by goksubaser** [comment]
Everything seems fine for system requirements but we need to fill glossary also and order them by alphabet. Can you check if there are unclear words in system requirements section and define them in the glossary in the context of the project? Then we can close this issue.

**Comment by nursimacelik** [comment]
Task: Updating the system requirements considering [questions](https://github.com/bounswe/bounswe2020group8/wiki/Questions) and [customer meeting answers](https://docs.google.com/document/d/1eJm5ai0pdeRBiODS9jh18abxF2JIHW-qEmgYmGpUONk/edit?usp=sharing). Deadline is 08.03.2020
