### ISSUE TITLE
Backend method change from GET to POST for /product/search and /product/searchFilters

### ISSUE THREAD

**Issue by nursimacelik** [bounswe/bounswe2020group8#312]
**Describe the bug**
Currently, the search endpoints are called with GET method. But they also require query inside the body. (See #302)
* GET /product/search
* GET /product/searchFilters

In Android, we use retrofit2, which doesn't allow adding Body to a request that uses GET method. While we can circumnavigate the issue with a custom annotation, it could be a better solution to use POST method for these endpoints.

**Comment by mtyazici** [comment]
Issue is solved and PR is merged.
