### ISSUE TITLE
Add customer meeting #1 notes

### ISSUE THREAD

**Issue by nursimacelik** [bounswe/bounswe2020group8#38]
We had a meeting with our customer today. Everybody asked their questions and Yasin took meeting notes. Now we should add these notes to wiki.

You can merge or split questions, edit them, write additional information as you like. 

[Here](https://github.com/bounswe/bounswe2020group8/wiki/Customer-Meeting-%231) is the document.

[Customer meeting answers](https://docs.google.com/document/d/1eJm5ai0pdeRBiODS9jh18abxF2JIHW-qEmgYmGpUONk/edit?usp=sharing)

**Comment by nursimacelik** [comment]
@ykaya932 I started but it would be better if you could complete. I must edit requirements that I wrote previously. If it is not suitable, you can reassign to somebody else.

**Comment by afraarslan** [comment]
I added answers on the questions page. You can continue on [this page](https://github.com/bounswe/bounswe2020group8/wiki/Questions)

Also, some details can be added to the customer meeting page

**Comment by ykaya932** [comment]
I couldn't come up with details for the customer meeting page but adding link to the page created by @afra-akbas. Any ideas what could be added?
