### ISSUE TITLE
Research Class Diagram

### ISSUE THREAD

**Issue by burakberk** [bounswe/bounswe2020group8#39]
Research class diagrams and get deeper understanding of them.

- [x] @ykaya932 

- [x] @burakberk 

- [x] @goksubaser 

- [x] @oguzhanozboyaci

**Comment by ykaya932** [comment]
We have finished our research, therefore I am closing the issue. I am also leaving a link that we found very useful: https://www.youtube.com/watch?v=UI6lqHOVHic
