### ISSUE TITLE
Creating Class Diagram

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#40]
This week we need to create the class diagram. Since the group study is necessary, I am leaving a doodle to set a date to work together.

**Comment by ykaya932** [comment]
Here is the doodle link, please select your options @burakberk @goksubaser @oguzhanozboyaci. I will close the doodle on 13.03.2020 at 13.00.
https://doodle.com/poll/874ssz3nebrqaksz

**Comment by burakberk** [comment]
Class diagram is complete and can be reached from here: https://github.com/bounswe/bounswe2020group8/wiki/Class-Diagram
