### ISSUE TITLE
Error occurred in /vendor/me endpoint

### ISSUE THREAD

**Issue by afraarslan** [bounswe/bounswe2020group8#429]
**Describe the bug**
When we send a get request to the `/vendor/me` endpoint, it gives 400 bad request error.

**To Reproduce**
In the Postman
1. Enter the vendor token as Bearer Token in the Authorization section
2. Send GET request to `/vendor/me`

**Expected behavior**
It  should give the vendor profile info in the response

**Comment by mtyazici** [comment]
I fixed the problem, when the PR passes we can close this issue.

**Comment by mtyazici** [comment]
PR is merged, I am closing this issue.
