### ISSUE TITLE
Creating Use Case Diagram

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#43]
This week we need to create the use case diagram that shows the interaction between users and the functionality they may perform. If the group study is necessary, you can make a doodle to decide the date.

**Comment by afraarslan** [comment]
I designed a use case diagram and added on [this page](https://github.com/bounswe/bounswe2020group8/wiki/Use-Case-Diagram)

**Comment by ykaya932** [comment]
@afra-akbas Could you remove the link from the page? Because now everyone can edit the diagram, and I guess it is better to give only view access to everyone.

**Comment by afraarslan** [comment]
Okay, I changed it.
