### ISSUE TITLE
Vendor order history can't be fetched.

### ISSUE THREAD

**Issue by burakberk** [bounswe/bounswe2020group8#450]
**Describe the bug**
Vendor's can't access their orders.

**Possible code location**
backend/dataAccess/getOrderByVendorIdDB

**To Reproduce**
Send get request to url/vendor/order/main

**Expected behavior**
All order's of logeed in vendor should be returned.

**Additional context**
Order model updated after implementation of getOrderByVendorIdDB

**Comment by burakberk** [comment]
Bug hot fixed with [this PR.](https://github.com/bounswe/bounswe2020group8/pull/451) Waiting for deployment to test on live server.

**Comment by oncelkeles** [comment]
This seems to be working just fine, thanks 👍
