### ISSUE TITLE
Review Class and Sequence Diagrams

### ISSUE THREAD

**Issue by nursimacelik** [bounswe/bounswe2020group8#46]
We will work on [class diagram](https://github.com/bounswe/bounswe2020group8/wiki/Class-Diagram) and [sequence diagrams](https://github.com/bounswe/bounswe2020group8/wiki/Sequence-Diagram) together, as they are very much related. Design and diagrams will be reviewed according to the [feedbacks](https://piazza.com/class/k5z7hzm7ncm1m3?cid=91).

**Comment by ykaya932** [comment]
Sequence Diagram & Class Diagram according to feedbacks. Then, I am closing this issue.
