### ISSUE TITLE
Deciding your own APIs

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#58]
Decide what will your own APIs look like and what external API that you will use during the implementation of your own APIs until 11th of May 2020. Do not forget to apply for API keys since it may take a long time to obtain. 

Then, write down the external API and your own API in the comments.

**Comment by mericturan** [comment]
Up :)

**Comment by nursimacelik** [comment]
I implemented a very simple recommendation system using [this algorithm](https://www.toptal.com/algorithms/predicting-likes-inside-a-simple-recommendation-engine). If I have time, I will consider implementing a more sophisticated one.

I have got API key of Spotify, will use it. (Not related to our project though)

**Comment by ykaya932** [comment]
I and @goksubaser are working on API that estimates the shipment price given the coordinates. We are using Google Maps APIs to get the customer's city and country information. Then by comparing it with the products' location, we are showing some estimation price.

**Comment by afraarslan** [comment]
I have decided to implement a search API, which finds products related to the specified query string. I took an API key from eBay and used the eBay catalog for products.

**Comment by burakberk** [comment]
I have decided to create COVID-19 country statistic api. For this purpose I have utilized the api in the [link](https://documenter.getpostman.com/view/10808728/SzS8rjbc?version=latest#9739c95f-ef1d-489b-97a9-0a6dfe2f74d8) .The api I have used does not requires a key to be used.
