### ISSUE TITLE
Favourite repo with description

### ISSUE THREAD

**Issue by nursimacelik** [bounswe/bounswe2020group8#6]
Closing the issue as it is duplicate.

**Comment by ykaya932** [comment]
After describing why you chose that repo as your favorite, please check the box near the your name. After everyone completes the task, we can close the issue.

- [x] Afra Akbaş

- [] Burak Berk Özer

- [ ] Ali Alperen Durak

- [x] Emre Yılmaz

- [x] Nursima Çelik

- [] Onur Enginer

- [ ] Ömer Topuz

- [x] Yasin Kaya

- [] Oğuzhan Özboyacı

- [] Göksu Başer
