### ISSUE TITLE
AWS Deployments

### ISSUE THREAD

**Issue by goksubaser** [bounswe/bounswe2020group8#72]
Yasin and Göksu will deploy the API project to the AWS and post the working url

**Comment by goksubaser** [comment]
"http://35.176.181.234/shipment_calculator/40.0_30.0/" This URL lists all the products in the database with the calculated shipment prices.
"http://35.176.181.234/shipment_calculator/add_vendor/" This URL provides an interface to create a vendor with coordinate values.
"http://35.176.181.234/shipment_calculator/add_product/" This URL provides an interface to create a product with vendor field.

**Comment by goksubaser** [comment]
I am leaving this issue open and reassigning other members to fill here with the other API's working URL's.

**Comment by nursimacelik** [comment]
You can insert 1 for customer-id, and a number in the range 1-13 for product-id.

- http://35.176.181.234/recommend/customers/
 http://35.176.181.234/recommend/customer/new/
 http://35.176.181.234/recommend/customer/detail/customer-id

- http://35.176.181.234/recommend/products/
http://35.176.181.234/recommend/product/new/
http://35.176.181.234/recommend/product/product-id/

- http://35.176.181.234/recommend/orderedproducts/customer-id
example: http://35.176.181.234/recommend/orderedproducts/1

- http://35.176.181.234/recommend/customer/customer-id/
example: http://35.176.181.234/recommend/customer/1/
(Normally returns the top 3 recommended products specific to customer-id. But for it to work properly, there should be other customers and products they bought, which can be added through customer/new.)

- http://35.176.181.234/recommend/album/
(Returns a recommended album assuming you bought the album mentioned.)

**Comment by afraarslan** [comment]
'http://35.176.181.234/sarch' 
return the list of products that contain the given keyword.
