### ISSUE TITLE
Add Project Divisions & Tools:

### ISSUE THREAD

**Issue by oztasoi** [bounswe/bounswe2020group8#82]
**Documentation description:**
It is needed to specify the project divisions and tools that are planned to use in further times. This issue is opened to review the explanation and give feedback about it.

**Document source**:
[Project Divisions & Tools](https://github.com/bounswe/bounswe2020group8/wiki/Project-Divisions-&-Tools)

**Comment by oncelkeles** [comment]
Nicely done! Well and simply phrased.

**Comment by ahmetyigitgedik** [comment]
nice work!
