### ISSUE TITLE
Add Revisions of Lab Meeting #1 (27.10.2020)

### ISSUE THREAD

**Issue by oztasoi** [bounswe/bounswe2020group8#84]
**Documentation description:**
Lab notes were taken at 27.10.2020, necessary revisions are done by Özgürcan Öztaş.

**Document source**:
[Requirements Update](https://github.com/bounswe/bounswe2020group8/wiki/Requirements/_compare/44bb5f7d71ede8112cf02a51bf970cde721ca2a5...59279fc058ddda7cdbe1f4287c0319ea3358f27a)

**Comment by oncelkeles** [comment]
WP 👏

**Comment by mtyazici** [comment]
Good job 👍
