### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#85]
**Documentation description:**
After a discussion with the team, we've decided on our project plan. Yet, the project plan needs to be imported to either ProjectLibre or Microsoft Projects. The deadline for this task is 07.11.2020. 

**Document source**:
https://docs.google.com/spreadsheets/d/1nWzgpoKbpbMr30RRlbOMJINDnAKPOU-UKyblHG3HOnY/edit#gid=0

**Comment by oztasoi** [comment]
@nursimacelik Amazing work, details are sufficient and the order is well-designed 🚀
