### ISSUE TITLE
Sequence Diagram Revision

### ISSUE THREAD

**Issue by ahmetyigitgedik** [bounswe/bounswe2020group8#86]
**Documentation description:**
To give the last shape of the sequence diagram after the class diagram is completed.

**Deadline**: 11.11.2020

**Document source**:
[Sequence Diagram](https://github.com/bounswe/bounswe2020group8/wiki/Sequence-Diagrams)

**Comment by kaandura** [comment]
Class diagram is completed, [issue link](https://github.com/bounswe/bounswe2020group8/issues/87). Now it's your turn

**Comment by afraarslan** [comment]
We did Google Meet and split the tasks.

* **Afra**->  review of *Comment*, and *Purchase Order*
* **Berke** -> review of *Cancel Order*, and *Add Product*
* **Onur** -> review of *Confirm Products*, *Add to Cart* and *Check Messages*
* **Ahmet Yiğit** -> create *Search for a Product*
* **Göksu** -> create *Report User*

**Comment by afraarslan** [comment]
I finished the Revision of **Comment** and **Purchase Order**. I uploaded images onto the Sequence Diagram page in the wiki.

**Comment by OnurEnginer** [comment]
I also revised *Confirm Products* , *Add to Cart* and *Check Messages* sequence diagrams according to changes in class diagram.

**Comment by ahmetyigitgedik** [comment]
I have created the _**Search for a Product**_ sequence diagram according to the updated class diagram and added it to the Sequence Diagram page in the wiki.

**Comment by nbmetin** [comment]
I have created the Add Product and Cancel Order diagrams and added them to wiki.

**Comment by goksubaser** [comment]
I have created the _**Report User**_ diagram depending on the changes in the class diagram and added them to wiki.
