### ISSUE TITLE
Class Diagram Revision

### ISSUE THREAD

**Issue by ykaya932** [bounswe/bounswe2020group8#87]
**Documentation description:**
The Class Diagram needs to be revisited with the Backend team and should be finalized. 

**Deadline**
08.11.2020

**Document source**:
Old class diagram: https://github.com/bounswe/bounswe2020group8/wiki/Class-Diagram

**Comment by oztasoi** [comment]
We've decided to separate all classes into several APIs and completed the analysis of the main classes in the main API that serves primary informations. Notifications, messaging, recommendation and search engine are planned to implement as different APIs. 👍

**Comment by oncelkeles** [comment]
Nice, thanks for the hard work guys 💪

**Comment by burakberk** [comment]
We have planned to implement messaging engine by transforming messaging interface, also planned to implement a documentation engine in order to help other teams integrate their work seamlessly. Updated search filters by adding categories and tags.
