### ISSUE TITLE
Add Revisions of Meeting #12 (28.10.2020)

### ISSUE THREAD

**Issue by oncelkeles** [bounswe/bounswe2020group8#88]
**Documentation description:**
Requirements should be updated according to notes taken at meeting #12.

**Document source**:
[Requirements](https://github.com/bounswe/bounswe2020group8/wiki/Requirements)

**Comment by oncelkeles** [comment]
Already done, very nice 💯

**Comment by oztasoi** [comment]
@burakberk nice job, very well explained! 🚀

**Comment by ykaya932** [comment]
Thanks, 🆒!
