### ISSUE TITLE
Upload Class Diagram

### ISSUE THREAD

**Issue by mtyazici** [bounswe/bounswe2020group8#89]
**Documentation description:**
Class diagram is revised and updated on lucidchart, it should be uploaded to wiki page. More detailed information in issue #87.

**Deadline**
05.11.2020

**Document source**:
New class diagram:  https://lucid.app/invitations/accept/3c848e0a-9be8-4d11-88cf-6fde787df7a4

**Comment by oztasoi** [comment]
It is updated in [here](https://github.com/bounswe/bounswe2020group8/wiki/Class-Diagram). Well done everyone! :shipit:
