### ISSUE TITLE
Edit repository examples page

### ISSUE THREAD

**Issue by nursimacelik** [bounswe/bounswe2020group8#9]
Add a description of what you like about the repository you've chosen considering the professor's comments and highlights. Here are some points we may consider:

* How is README page? (logo, images, flowcharts, contribution section, etc.)
* How detailed and helpful is wiki? (home page and other documents)
* Issues section (explanations, labels, discussion)

If there is anything I'm missing, feel free to add.

Link: [repo examples](https://github.com/bounswe/bounswe2020group8/wiki/Repository-Examples)

- [x] Afra Akbaş

- [x] Göksu Başer

- [x] Onur Enginer

- [x] Yasin Kaya

- [x] Oğuzhan Özboyacı

- [x] Burak Berk Özerk

- [x] Alperen Durak

- [x] Nursima Çelik

- [x] Emre Yılmaz

- [x] Ömer Topuz

**Comment by ykaya932** [comment]
Deadline Sunday 23.59
