### ISSUE TITLE
Update README and Group Photo

### ISSUE THREAD

**Issue by burakberk** [bounswe/bounswe2020group8#90]
With the newcomers to the team, README and group photo needs to be updated.

**Comment by oncelkeles** [comment]
Let's get this done in our next lab meeting!

**Comment by oncelkeles** [comment]
New group photo can be found here:

<img width="1440" alt="CMPE451-GroupPhoto" src="https://user-images.githubusercontent.com/31131763/100743195-08a18180-33ed-11eb-8b5d-6d73456343fd.png">

**Comment by afraarslan** [comment]
I think we should change our ReadMe page this week.

**Comment by oztasoi** [comment]
I'll do it tonight, and inform you about the update 💻
